Beff=1/80;
Jm=1/100;
m=15; %kg
r=1/200;
Jeff=Jm*square(r)*m;
Km_R=0.3;
% wn=sqrt((Kp*Km)/(Jeff*R))
% e=(Beff+Kd*Km_R)/(2*Jeff*wn)
% Kd=(2*Jeff*wn-Beff)/(Km_R)
A=1/2;
Kp=(4*Jeff)/(square(A)*Km_R);
Kd=((4*Jeff)/A-Beff)/Km_R;